In [1]:
import torch

In [3]:
from deep_learning.models.feature_extractors.resnet import Resnet50

model= Resnet50()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
model.to(device)

random_input = torch.randn(200, 3, 256, 256).to(device)

model.eval()
with torch.no_grad():
    features = model(random_input)

print(features.shape)

cuda
torch.Size([200, 2048, 1, 1])


In [ ]:
from deep_learning.models.feature_extractors.efficientnet import EfficientNetB1

model= EfficientNetB1()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
model.to(device)

random_input = torch.randn(200, 3, 256, 256).to(device)

model.eval()
with torch.no_grad():
    features = model(random_input)

print(features.shape)

c:\Users\user\.julia\conda\3\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\user\.julia\conda\3\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=EfficientNet_B1_Weights.IMAGENET1K_V1`. You can also use `weights=EfficientNet_B1_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


cuda
torch.Size([200, 1280, 1, 1])


In [3]:
import torch
import os
from deep_learning.feature_extraction import extract_features
from deep_learning.models.transforms.transforms import transform_resnet
from deep_learning.models.feature_extractors.resnet import Resnet50
from deep_learning.loaders.image_batch_loader import load_batch_from_dir
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model=Resnet50().to(device)

features=extract_features(model,transform_resnet,"F:/test/0005f7aaab2800f6170c399693a96917/tiles")
torch.save(features,"F:/test/0005f7aaab2800f6170c399693a96917.pt")


c:\Users\user\.julia\conda\3\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\user\.julia\conda\3\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [5]:
import pandas as pd

# Example DataFrame (assuming it’s loaded from a CSV)
df = pd.DataFrame({
    "feature_path": ["features/img1.npy", "features/img2.npy", "features/img3.npy"],
    "label": [0, 1, 0]
})
df["feature_path"][0]

'features/img1.npy'

In [4]:
from deep_learning.loaders.feature_dataset import FeatureDataset
import pandas as pd
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader

df=pd.read_csv("F:/data/small.csv")
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

print("Train size:", len(train_df))
print("Test size:", len(test_df))

dataset=FeatureDataset(train_df,"F:/extracted_features")

train_loader = DataLoader(dataset, shuffle=True)

print(f"Train batches: {len(train_loader)}")

for batch in train_loader:
    x_batch, y_batch = batch
    x_batch=x_batch.squeeze()
    print("Batch X shape:", x_batch.shape)  # Expected: (32, D)
    print("Batch Y shape:", y_batch.squeeze().shape)  # Expected: (32,)
    break  # Only one batch

Train size: 760
Test size: 191
Train batches: 760
Batch X shape: torch.Size([193, 2048])
Batch Y shape: torch.Size([])


In [5]:
from deep_learning.models.attention_core.clam import Clam
import torch
from torchinfo import summary

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=5,
    subtyping=True
)

model.to(device)
summary(model, input_size=(100,2048))

Layer (type:depth-idx)                   Output Shape              Param #
Clam                                     [1, 5]                    5,130
├─Sequential: 1-1                        [100, 5]                  --
│    └─Linear: 2-1                       [100, 512]                1,049,088
│    └─ReLU: 2-2                         [100, 512]                --
│    └─Dropout: 2-3                      [100, 512]                --
│    └─Attn_Net_Gated: 2-4               [100, 5]                  --
│    │    └─Sequential: 3-1              [100, 256]                131,328
│    │    └─Sequential: 3-2              [100, 256]                131,328
│    │    └─Linear: 3-3                  [100, 5]                  1,285
├─ModuleList: 1-2                        --                        --
│    └─Linear: 2-5                       [1]                       513
│    └─Linear: 2-6                       [1]                       513
│    └─Linear: 2-7                       [1]                

In [16]:
for batch in train_loader:
    x_batch, y_batch = batch
    x_batch=x_batch.squeeze()
    x_batch.to(device)
    logits, Y_prob, Y_hat, A_raw, results_dict=model(x_batch)
    print(logits)
    break  # Only one batch

tensor([[ 0.0363, -0.0058,  0.0846, -0.0593,  0.0797]], device='cuda:0',
       grad_fn=<CopySlices>)


In [1]:
from deep_learning.loaders.feature_dataset import FeatureDataset
import pandas as pd
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/small.csv")
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model,train_df,"F:/extracted_features",3)



batch 19, loss: 2.6146, instance_loss: 0.7178, weighted_loss: 1.6662, label: 2, bag_size: 198
batch 39, loss: 1.7910, instance_loss: 0.6853, weighted_loss: 1.2382, label: 5, bag_size: 145
batch 59, loss: 2.4337, instance_loss: 0.7029, weighted_loss: 1.5683, label: 3, bag_size: 128
batch 79, loss: 1.0695, instance_loss: 0.5800, weighted_loss: 0.8247, label: 1, bag_size: 395
batch 99, loss: 3.1832, instance_loss: 0.6473, weighted_loss: 1.9152, label: 2, bag_size: 184
batch 119, loss: 1.7686, instance_loss: 0.5912, weighted_loss: 1.1799, label: 1, bag_size: 246
batch 139, loss: 2.1358, instance_loss: 0.6433, weighted_loss: 1.3895, label: 3, bag_size: 167
batch 159, loss: 1.2676, instance_loss: 0.3248, weighted_loss: 0.7962, label: 0, bag_size: 236
batch 179, loss: 2.4001, instance_loss: 0.8914, weighted_loss: 1.6457, label: 5, bag_size: 134
batch 199, loss: 2.4610, instance_loss: 0.6065, weighted_loss: 1.5337, label: 2, bag_size: 225
batch 219, loss: 1.2204, instance_loss: 0.5954, weigh

In [2]:
import numpy as np
from deep_learning.utils.metrics import quadratic_weighted_kappa,compute_precision_recall_f1
y_true = np.array([0, 1, 2, 2, 3, 3, 4, 4, 5, 5]) 
y_pred = np.array([0, 1, 2, 3, 3, 2, 4, 3, 5, 5])

qwk_score = quadratic_weighted_kappa(y_true=y_true, y_pred=y_pred, num_classes=6)
print(f"Quadratic Weighted Kappa: {qwk_score:.4f}")
conf_matrix = np.array([
    [50,  2,  1,  0,  0,  1],  # Class 0
    [ 3, 45,  5,  2,  1,  0],  # Class 1
    [ 0,  4, 40,  7,  2,  1],  # Class 2
    [ 0,  0,  3, 50,  4,  2],  # Class 3
    [ 0,  1,  2,  5, 45,  5],  # Class 4
    [ 1,  0,  1,  3,  2, 47]   # Class 5
])
print(compute_precision_recall_f1(conf_matrix))

Quadratic Weighted Kappa: 0.9383
tensor([50, 45, 40, 50, 45, 47], dtype=torch.int32)
tensor([ 4,  7, 12, 17,  9,  9])
tensor([ 4, 11, 14,  9, 13,  7])
(tensor([0.9259, 0.8654, 0.7692, 0.7463, 0.8333, 0.8393]), tensor([0.9259, 0.8036, 0.7407, 0.8475, 0.7759, 0.8704]), tensor([0.9259, 0.8333, 0.7547, 0.7937, 0.8036, 0.8545]), 0.8276239037513733, 0.8268638253211975)


In [ ]:
import pandas as pd
import torch
from deep_learning.loaders.feature_dataset import FeatureDataset
from torch.utils.data import DataLoader

from deep_learning.models.attention_core.clam import Clam
from deep_learning.services.attention_score_service import get_best_attention_scores
df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)

model.load_state_dict(torch.load("F:/logs/resnet_clam/20250306_220754_p7_b75/model_weights_14.pth"))

df=pd.read_csv("F:/data/train_stratified.csv")
feature_path="F:/extracted_features_resnet"
dataset=FeatureDataset(df,feature_path)
data_loader=DataLoader(dataset, batch_size=1, shuffle=True,num_workers=0)
features,label=next(iter(data_loader))

print(f"Label:{label}")
best_scores=get_best_attention_scores(model, features);
score_df=pd.DataFrame(best_scores)
cat_counts=score_df["prediction"].value_counts()
print(cat_counts)

Label:tensor([4])
Y_hat: 4, Y_prob: ['0.0000', '0.0001', '0.0031', '0.1960', '0.5492', '0.2516']
tensor([[2.5718e-05, 7.2330e-05, 3.1172e-03, 1.9599e-01, 5.4920e-01, 2.5159e-01]],
       device='cuda:0')
3    72
5    46
0    43
4    11
1     6
2     1
Name: prediction, dtype: int64


In [12]:
import torch
import pandas as pd
from deep_learning.models.attention_core.clam import Clam
from deep_learning.services.attention_score_service import (get_best_attention_scores,
                               get_tiles_coords,pair_coords_and_attention_scores,get_min_max_coordinates)

from deep_learning.services.file_and_data_service import FileDataService
from deep_learning.services.attention_visualization_service import ImageComposer
model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)

model.load_state_dict(torch.load("F:/logs/resnet_clam/20250306_220754_p7_b75/model_weights_14.pth"))

slide_name="1d3d8045a44963e4367b437fdf361dc5"
feature_path="F:/extracted_features_resnet"
fd=FileDataService(feature_path)
tiles_path=f"F:/extracted/{slide_name}/tiles"

output_path=f"F:/output/{slide_name}"

#Data Preparation
features=fd.load_image_features(slide_name)

best_scores=get_best_attention_scores(model, features)
coords=get_tiles_coords(tiles_path)
data=pair_coords_and_attention_scores(best_scores,coords)
min_max_coords=get_min_max_coordinates(data)

img_composer=ImageComposer(256,min_max_coords,data)
img_composer.create_composed_images(tiles_path,output_path)

score_df=pd.DataFrame(best_scores)
cat_counts=score_df["predicted_label"].value_counts()
print(cat_counts)

Y_hat: 5, Y_prob: ['0.0012', '0.0002', '0.0001', '0.0039', '0.0947', '0.8998']
tensor([[1.2234e-03, 1.7128e-04, 1.0321e-04, 3.9496e-03, 9.4715e-02, 8.9984e-01]],
       device='cuda:0')
3    80
4     4
0     3
2     3
5     1
Name: predicted_label, dtype: int64


In [20]:
import torch
import pandas as pd
from deep_learning.models.attention_core.clam import Clam
from deep_learning.services.attention_score_service import (get_best_attention_scores,
                               get_tiles_coords,pair_coords_and_attention_scores,get_min_max_coordinates)

from deep_learning.services.file_and_data_service import FileDataService
from deep_learning.services.attention_visualization_service import ImageComposer
model=Clam(
    feature_vector_length=1280,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)

model.load_state_dict(torch.load("F:/logs/effnet_clam/20250306_223024_p7_b75/model_weights_4.pth"))

slide_name="c071c418f185ef8191b4eddb6efcc316"
feature_path="F:/extracted_features_effnet"
fd=FileDataService(feature_path)
tiles_path=f"F:/extracted/{slide_name}/tiles"

output_path=f"F:/output_effnet/{slide_name}"

#Data Preparation
features=fd.load_image_features(slide_name)

best_scores=get_best_attention_scores(model, features)
coords=get_tiles_coords(tiles_path)
data=pair_coords_and_attention_scores(best_scores,coords)
min_max_coords=get_min_max_coordinates(data)

img_composer=ImageComposer(256,min_max_coords,data)
img_composer.create_composed_images(tiles_path,output_path)

score_df=pd.DataFrame(best_scores)
cat_counts=score_df["predicted_label"].value_counts()
print(cat_counts)

Y_hat: 1, Y_prob: ['0.1931', '0.5989', '0.1644', '0.0364', '0.0017', '0.0056']
tensor([[0.1931, 0.5989, 0.1644, 0.0364, 0.0017, 0.0056]], device='cuda:0')
5    160
4      7
0      6
3      1
Name: predicted_label, dtype: int64
