In [1]:
from deep_learning.loaders.feature_dataset import FeatureDataset
import pandas as pd
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/small.csv")
train_df, test_df = train_test_split(df[:100], test_size=0.2, random_state=42)

model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model,train_df,"F:/extracted_features",10,1,"F:/logs/resnet_clam_small")



Epoch 0 Summary: train_loss: 1.7303, train_clustering_loss:  0.6848, train_accuracy: 0.2031
Macro-F1: 0.1174; Weighted F1:0.1869
Slide Accuracy:
class 0: acc 0.19047619047619047, correct 4/21
class 1: acc 0.4444444444444444, correct 8/18
class 2: acc 0.125, correct 1/8
class 3: acc 0.0, correct 0/6
class 4: acc 0.0, correct 0/6
class 5: acc 0.0, correct 0/5
[[ 4. 12.  0.  4.  1.  0.]
 [ 6.  8.  1.  3.  0.  0.]
 [ 0.  4.  1.  1.  2.  0.]
 [ 0.  3.  2.  0.  1.  0.]
 [ 2.  1.  2.  1.  0.  0.]
 [ 1.  3.  0.  1.  0.  0.]]
Quadratic Weighted Kappa: 0.0596

Val Set, val_loss: 1.6745, val_accuracy: 0.2500
Macro-F1: 0.1005; Weighted F1:0.1792
class 0: acc 0.3333333333333333, correct 1/3
class 1: acc 0.5, correct 3/6
class 2: acc 0.0, correct 0/4
class 3: acc 0.0, correct 0/1
class 4: acc 0.0, correct 0/2
class 5: acc None, correct 0/0
[[1. 2. 0. 0. 0. 0.]
 [3. 3. 0. 0. 0. 0.]
 [1. 3. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Quadratic Weighted Kappa: 0.1420


In [ ]:
# import pandas as pd
# from sklearn.model_selection import train_test_split

# df=pd.read_csv("F:/data/train_noise_removed_cleaned.csv")
# train_df, test_df = train_test_split(df, test_size=0.1, random_state=42, stratify=df["isup_grade"])

# train_df.to_csv("F:/data/train_stratified.csv")
# test_df.to_csv("F:/data/test_stratified.csv")

### RESNET BASED FEATURES TRAINING

In [1]:
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model,df,"F:/extracted_features_resnet",100,5,"F:/logs/resnet_clam")



batch 499, loss: 1.8346, instance_loss: 0.3958, weighted_loss: 1.1152, 
batch 999, loss: 0.8376, instance_loss: 0.0870, weighted_loss: 0.4623, 
batch 1499, loss: 0.5775, instance_loss: 0.0375, weighted_loss: 0.3075, 
batch 1999, loss: 0.3443, instance_loss: 0.0188, weighted_loss: 0.1816, 
batch 2499, loss: 0.5143, instance_loss: 0.0088, weighted_loss: 0.2616, 
batch 2999, loss: 1.2305, instance_loss: 0.0279, weighted_loss: 0.6292, 
batch 3499, loss: 1.9715, instance_loss: 0.0337, weighted_loss: 1.0026, 
batch 3999, loss: 1.3845, instance_loss: 0.0131, weighted_loss: 0.6988, 
batch 4499, loss: 0.9493, instance_loss: 0.1088, weighted_loss: 0.5290, 
batch 4999, loss: 3.0422, instance_loss: 0.0942, weighted_loss: 1.5682, 
batch 5499, loss: 1.1025, instance_loss: 0.0146, weighted_loss: 0.5585, 
batch 5999, loss: 0.4268, instance_loss: 0.3316, weighted_loss: 0.3792, 
batch 6499, loss: 1.2984, instance_loss: 0.0218, weighted_loss: 0.6601, 
Epoch 0 Summary: train_loss: 1.2878, train_clusteri

In [3]:
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_resnet",
      epochs=100,
      patience=7,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/resnet_clam")



batch 499, loss: 1.9241, instance_loss: 0.5037, weighted_loss: 1.5690, 
batch 999, loss: 1.6972, instance_loss: 0.2473, weighted_loss: 1.3347, 
batch 1499, loss: 1.1152, instance_loss: 0.3830, weighted_loss: 0.9322, 
batch 1999, loss: 1.2598, instance_loss: 0.1120, weighted_loss: 0.9728, 
batch 2499, loss: 0.1626, instance_loss: 0.1567, weighted_loss: 0.1611, 
batch 2999, loss: 1.4048, instance_loss: 0.0145, weighted_loss: 1.0572, 
batch 3499, loss: 1.2046, instance_loss: 0.0208, weighted_loss: 0.9086, 
batch 3999, loss: 0.4117, instance_loss: 0.0263, weighted_loss: 0.3153, 
batch 4499, loss: 4.8394, instance_loss: 0.3046, weighted_loss: 3.7057, 
batch 4999, loss: 0.9289, instance_loss: 0.0683, weighted_loss: 0.7137, 
batch 5499, loss: 1.4774, instance_loss: 0.0283, weighted_loss: 1.1151, 
batch 5999, loss: 1.4483, instance_loss: 0.0725, weighted_loss: 1.1043, 
batch 6499, loss: 1.4767, instance_loss: 0.0942, weighted_loss: 1.1311, 
Epoch 0 Summary: train_loss: 1.3148, train_clusteri

### EFFICIENTNET BASED FEATURES TRAINING

In [1]:
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=1280,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_effnet",
      epochs=100,
      patience=5,
      min_delta=0.005,
      bag_weight=0.5,
      log_dir="F:/logs/effnet_clam")



batch 499, loss: 0.6291, instance_loss: 0.0425, weighted_loss: 0.3358, 
batch 999, loss: 1.7452, instance_loss: 0.0298, weighted_loss: 0.8875, 
batch 1499, loss: 1.2208, instance_loss: 0.1576, weighted_loss: 0.6892, 
batch 1999, loss: 1.1624, instance_loss: 0.0215, weighted_loss: 0.5920, 
batch 2499, loss: 1.3728, instance_loss: 0.0861, weighted_loss: 0.7295, 
batch 2999, loss: 3.6389, instance_loss: 0.0528, weighted_loss: 1.8458, 
batch 3499, loss: 1.3116, instance_loss: 0.0043, weighted_loss: 0.6579, 
batch 3999, loss: 0.0648, instance_loss: 0.0217, weighted_loss: 0.0432, 
batch 4499, loss: 0.6314, instance_loss: 0.0809, weighted_loss: 0.3561, 
batch 4999, loss: 1.7526, instance_loss: 0.0125, weighted_loss: 0.8825, 
batch 5499, loss: 0.3337, instance_loss: 0.0039, weighted_loss: 0.1688, 
batch 5999, loss: 0.1363, instance_loss: 0.1305, weighted_loss: 0.1334, 
batch 6499, loss: 0.8456, instance_loss: 0.0118, weighted_loss: 0.4287, 
Epoch 0 Summary: train_loss: 1.1151, train_clusteri

In [4]:
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=1280,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_effnet",
      epochs=100,
      patience=7,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/effnet_clam")



batch 499, loss: 1.6534, instance_loss: 0.1576, weighted_loss: 1.2795, 
batch 999, loss: 0.2157, instance_loss: 0.0696, weighted_loss: 0.1792, 
batch 1499, loss: 2.3874, instance_loss: 0.0211, weighted_loss: 1.7959, 
batch 1999, loss: 1.3282, instance_loss: 0.0519, weighted_loss: 1.0091, 
batch 2499, loss: 0.1561, instance_loss: 0.0027, weighted_loss: 0.1178, 
batch 2999, loss: 0.1478, instance_loss: 0.0335, weighted_loss: 0.1193, 
batch 3499, loss: 0.4938, instance_loss: 0.0194, weighted_loss: 0.3752, 
batch 3999, loss: 0.2764, instance_loss: 0.0112, weighted_loss: 0.2101, 
batch 4499, loss: 0.5535, instance_loss: 0.0101, weighted_loss: 0.4177, 
batch 4999, loss: 1.6653, instance_loss: 0.0053, weighted_loss: 1.2503, 
batch 5499, loss: 3.8698, instance_loss: 0.1518, weighted_loss: 2.9403, 
batch 5999, loss: 1.5391, instance_loss: 0.0173, weighted_loss: 1.1586, 
batch 6499, loss: 0.5464, instance_loss: 0.0106, weighted_loss: 0.4124, 
Epoch 0 Summary: train_loss: 1.1108, train_clusteri