In [1]:
from deep_learning.loaders.feature_dataset import FeatureDataset
import pandas as pd
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/small.csv")
train_df, test_df = train_test_split(df[:100], test_size=0.2, random_state=42)

model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model,train_df,"F:/extracted_features",10,1,"F:/logs/resnet_clam_small")



Epoch 0 Summary: train_loss: 1.7303, train_clustering_loss:  0.6848, train_accuracy: 0.2031
Macro-F1: 0.1174; Weighted F1:0.1869
Slide Accuracy:
class 0: acc 0.19047619047619047, correct 4/21
class 1: acc 0.4444444444444444, correct 8/18
class 2: acc 0.125, correct 1/8
class 3: acc 0.0, correct 0/6
class 4: acc 0.0, correct 0/6
class 5: acc 0.0, correct 0/5
[[ 4. 12.  0.  4.  1.  0.]
 [ 6.  8.  1.  3.  0.  0.]
 [ 0.  4.  1.  1.  2.  0.]
 [ 0.  3.  2.  0.  1.  0.]
 [ 2.  1.  2.  1.  0.  0.]
 [ 1.  3.  0.  1.  0.  0.]]
Quadratic Weighted Kappa: 0.0596

Val Set, val_loss: 1.6745, val_accuracy: 0.2500
Macro-F1: 0.1005; Weighted F1:0.1792
class 0: acc 0.3333333333333333, correct 1/3
class 1: acc 0.5, correct 3/6
class 2: acc 0.0, correct 0/4
class 3: acc 0.0, correct 0/1
class 4: acc 0.0, correct 0/2
class 5: acc None, correct 0/0
[[1. 2. 0. 0. 0. 0.]
 [3. 3. 0. 0. 0. 0.]
 [1. 3. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Quadratic Weighted Kappa: 0.1420


In [ ]:
# import pandas as pd
# from sklearn.model_selection import train_test_split

# df=pd.read_csv("F:/data/train_noise_removed_cleaned.csv")
# train_df, test_df = train_test_split(df, test_size=0.1, random_state=42, stratify=df["isup_grade"])

# train_df.to_csv("F:/data/train_stratified.csv")
# test_df.to_csv("F:/data/test_stratified.csv")

### RESNET BASED FEATURES TRAINING

In [1]:
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model,df,"F:/extracted_features_resnet",100,5,"F:/logs/resnet_clam")



batch 499, loss: 1.8346, instance_loss: 0.3958, weighted_loss: 1.1152, 
batch 999, loss: 0.8376, instance_loss: 0.0870, weighted_loss: 0.4623, 
batch 1499, loss: 0.5775, instance_loss: 0.0375, weighted_loss: 0.3075, 
batch 1999, loss: 0.3443, instance_loss: 0.0188, weighted_loss: 0.1816, 
batch 2499, loss: 0.5143, instance_loss: 0.0088, weighted_loss: 0.2616, 
batch 2999, loss: 1.2305, instance_loss: 0.0279, weighted_loss: 0.6292, 
batch 3499, loss: 1.9715, instance_loss: 0.0337, weighted_loss: 1.0026, 
batch 3999, loss: 1.3845, instance_loss: 0.0131, weighted_loss: 0.6988, 
batch 4499, loss: 0.9493, instance_loss: 0.1088, weighted_loss: 0.5290, 
batch 4999, loss: 3.0422, instance_loss: 0.0942, weighted_loss: 1.5682, 
batch 5499, loss: 1.1025, instance_loss: 0.0146, weighted_loss: 0.5585, 
batch 5999, loss: 0.4268, instance_loss: 0.3316, weighted_loss: 0.3792, 
batch 6499, loss: 1.2984, instance_loss: 0.0218, weighted_loss: 0.6601, 
Epoch 0 Summary: train_loss: 1.2878, train_clusteri

In [3]:
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_resnet",
      epochs=100,
      patience=7,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/resnet_clam")



batch 499, loss: 1.9241, instance_loss: 0.5037, weighted_loss: 1.5690, 
batch 999, loss: 1.6972, instance_loss: 0.2473, weighted_loss: 1.3347, 
batch 1499, loss: 1.1152, instance_loss: 0.3830, weighted_loss: 0.9322, 
batch 1999, loss: 1.2598, instance_loss: 0.1120, weighted_loss: 0.9728, 
batch 2499, loss: 0.1626, instance_loss: 0.1567, weighted_loss: 0.1611, 
batch 2999, loss: 1.4048, instance_loss: 0.0145, weighted_loss: 1.0572, 
batch 3499, loss: 1.2046, instance_loss: 0.0208, weighted_loss: 0.9086, 
batch 3999, loss: 0.4117, instance_loss: 0.0263, weighted_loss: 0.3153, 
batch 4499, loss: 4.8394, instance_loss: 0.3046, weighted_loss: 3.7057, 
batch 4999, loss: 0.9289, instance_loss: 0.0683, weighted_loss: 0.7137, 
batch 5499, loss: 1.4774, instance_loss: 0.0283, weighted_loss: 1.1151, 
batch 5999, loss: 1.4483, instance_loss: 0.0725, weighted_loss: 1.1043, 
batch 6499, loss: 1.4767, instance_loss: 0.0942, weighted_loss: 1.1311, 
Epoch 0 Summary: train_loss: 1.3148, train_clusteri

### EFFICIENTNET BASED FEATURES TRAINING

In [1]:
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=1280,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_effnet",
      epochs=100,
      patience=5,
      min_delta=0.005,
      bag_weight=0.5,
      log_dir="F:/logs/effnet_clam")



batch 499, loss: 0.6291, instance_loss: 0.0425, weighted_loss: 0.3358, 
batch 999, loss: 1.7452, instance_loss: 0.0298, weighted_loss: 0.8875, 
batch 1499, loss: 1.2208, instance_loss: 0.1576, weighted_loss: 0.6892, 
batch 1999, loss: 1.1624, instance_loss: 0.0215, weighted_loss: 0.5920, 
batch 2499, loss: 1.3728, instance_loss: 0.0861, weighted_loss: 0.7295, 
batch 2999, loss: 3.6389, instance_loss: 0.0528, weighted_loss: 1.8458, 
batch 3499, loss: 1.3116, instance_loss: 0.0043, weighted_loss: 0.6579, 
batch 3999, loss: 0.0648, instance_loss: 0.0217, weighted_loss: 0.0432, 
batch 4499, loss: 0.6314, instance_loss: 0.0809, weighted_loss: 0.3561, 
batch 4999, loss: 1.7526, instance_loss: 0.0125, weighted_loss: 0.8825, 
batch 5499, loss: 0.3337, instance_loss: 0.0039, weighted_loss: 0.1688, 
batch 5999, loss: 0.1363, instance_loss: 0.1305, weighted_loss: 0.1334, 
batch 6499, loss: 0.8456, instance_loss: 0.0118, weighted_loss: 0.4287, 
Epoch 0 Summary: train_loss: 1.1151, train_clusteri

In [1]:
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=1280,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_effnet",
      epochs=100,
      patience=7,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/effnet_clam")

c:\Users\user\.julia\conda\3\lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(




M
torch.Size([6, 512])
Logits
torch.Size([1, 6])
tensor([[-0.1000,  0.0999, -0.1630, -0.1392, -0.1943, -0.0769]],
       device='cuda:0', grad_fn=<CopySlices>)
-------
tensor([[0.1651, 0.2017, 0.1551, 0.1588, 0.1503, 0.1690]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
-------
tensor([[1]], device='cuda:0')
-------
M
torch.Size([6, 512])
Logits
torch.Size([1, 6])
tensor([[-0.1138,  0.2286, -0.1265, -0.1425, -0.1021, -0.1136]],
       device='cuda:0', grad_fn=<CopySlices>)
-------
tensor([[0.1568, 0.2208, 0.1548, 0.1523, 0.1586, 0.1568]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
-------
tensor([[1]], device='cuda:0')
-------
M
torch.Size([6, 512])
Logits
torch.Size([1, 6])
tensor([[-0.0705,  0.3598, -0.1969, -0.1942, -0.1851, -0.1217]],
       device='cuda:0', grad_fn=<CopySlices>)
-------
tensor([[0.1627, 0.2503, 0.1434, 0.1438, 0.1451, 0.1546]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
-------
tensor([[1]], device='cuda:0')
-------
M
torch.Size([6, 512

: 

In [1]:
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import ClamSimple

df=pd.read_csv("F:/data/train_stratified.csv")

model=ClamSimple(
    feature_vector_length=1280,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_effnet",
      epochs=100,
      patience=7,
      min_delta=0.005,
      bag_weight=0.80,
      log_dir="F:/logs/effnet_clam")

c:\Users\user\.julia\conda\3\lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(




batch 499, loss: 2.6051, instance_loss: 0.1030, weighted_loss: 2.1047, 
batch 999, loss: 2.2412, instance_loss: 0.6100, weighted_loss: 1.9150, 
batch 1499, loss: 2.1592, instance_loss: 0.1452, weighted_loss: 1.7564, 
batch 1999, loss: 2.6117, instance_loss: 0.1360, weighted_loss: 2.1166, 
batch 2499, loss: 0.1915, instance_loss: 0.0058, weighted_loss: 0.1544, 
batch 2999, loss: 0.7995, instance_loss: 0.0724, weighted_loss: 0.6541, 
batch 3499, loss: 0.9905, instance_loss: 0.0301, weighted_loss: 0.7984, 
batch 3999, loss: 2.7805, instance_loss: 0.1477, weighted_loss: 2.2539, 
batch 4499, loss: 2.3789, instance_loss: 0.0062, weighted_loss: 1.9044, 
batch 4999, loss: 0.2512, instance_loss: 0.0006, weighted_loss: 0.2011, 
batch 5499, loss: 1.0320, instance_loss: 0.0022, weighted_loss: 0.8260, 
batch 5999, loss: 0.8466, instance_loss: 0.0063, weighted_loss: 0.6785, 
batch 6499, loss: 0.7541, instance_loss: 0.0017, weighted_loss: 0.6036, 
Epoch 0 Summary: train_loss: 1.2415, train_clusteri

In [ ]:
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=1280,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=True
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_effnet",
      epochs=100,
      patience=7,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/effnet_clam_subtyping")

c:\Users\user\.julia\conda\3\lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(




batch 499, loss: 0.9228, instance_loss: 0.1846, weighted_loss: 0.7382, 
batch 999, loss: 1.6773, instance_loss: 0.2561, weighted_loss: 1.3220, 
batch 1499, loss: 0.7052, instance_loss: 0.1839, weighted_loss: 0.5749, 
batch 1999, loss: 0.2539, instance_loss: 0.1858, weighted_loss: 0.2369, 
batch 2499, loss: 0.5224, instance_loss: 0.1637, weighted_loss: 0.4327, 
batch 2999, loss: 2.7022, instance_loss: 0.3448, weighted_loss: 2.1128, 
batch 3499, loss: 0.6068, instance_loss: 0.1983, weighted_loss: 0.5046, 
batch 3999, loss: 2.2275, instance_loss: 0.3439, weighted_loss: 1.7566, 
batch 4499, loss: 5.8406, instance_loss: 0.5109, weighted_loss: 4.5082, 
batch 4999, loss: 2.5397, instance_loss: 0.3039, weighted_loss: 1.9808, 
batch 5499, loss: 0.5840, instance_loss: 0.2140, weighted_loss: 0.4915, 
batch 5999, loss: 1.3545, instance_loss: 0.3106, weighted_loss: 1.0935, 
batch 6499, loss: 1.9747, instance_loss: 0.3394, weighted_loss: 1.5658, 
Epoch 0 Summary: train_loss: 1.1176, train_clusteri

: 

In [1]:
#efficientNet +Clam
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=1280,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_effnet",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/effnet_clam")

c:\Users\user\.julia\conda\3\lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(




batch 499, loss: 1.0008, instance_loss: 0.3648, weighted_loss: 0.8418, 
batch 999, loss: 2.0352, instance_loss: 0.0346, weighted_loss: 1.5350, 
batch 1499, loss: 0.5890, instance_loss: 0.0428, weighted_loss: 0.4525, 
batch 1999, loss: 0.5942, instance_loss: 0.0400, weighted_loss: 0.4557, 
batch 2499, loss: 0.3542, instance_loss: 0.1014, weighted_loss: 0.2910, 
batch 2999, loss: 2.3246, instance_loss: 0.0054, weighted_loss: 1.7448, 
batch 3499, loss: 1.7681, instance_loss: 0.0161, weighted_loss: 1.3301, 
batch 3999, loss: 0.2618, instance_loss: 0.0211, weighted_loss: 0.2016, 
batch 4499, loss: 1.1410, instance_loss: 0.0469, weighted_loss: 0.8675, 
batch 4999, loss: 1.4459, instance_loss: 0.0107, weighted_loss: 1.0871, 
batch 5499, loss: 0.6024, instance_loss: 0.0464, weighted_loss: 0.4634, 
batch 5999, loss: 0.3372, instance_loss: 0.0144, weighted_loss: 0.2565, 
batch 6499, loss: 0.2550, instance_loss: 0.0099, weighted_loss: 0.1938, 
Epoch 0 Summary: train_loss: 1.1320, train_clusteri

In [2]:
#efficientNet +ClamSimple
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam, ClamSimple

df=pd.read_csv("F:/data/train_stratified.csv")

model=ClamSimple(
    feature_vector_length=1280,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_effnet",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/effnet_clamsimple")

c:\Users\user\.julia\conda\3\lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(


batch 499, loss: 1.7427, instance_loss: 0.0149, weighted_loss: 1.3107, 
batch 999, loss: 0.7212, instance_loss: 0.0410, weighted_loss: 0.5512, 
batch 1499, loss: 1.6594, instance_loss: 0.0163, weighted_loss: 1.2486, 
batch 1999, loss: 1.1251, instance_loss: 0.0674, weighted_loss: 0.8607, 
batch 2499, loss: 1.1372, instance_loss: 0.0033, weighted_loss: 0.8538, 
batch 2999, loss: 2.7057, instance_loss: 0.1202, weighted_loss: 2.0593, 
batch 3499, loss: 0.3952, instance_loss: 0.0215, weighted_loss: 0.3018, 
batch 3999, loss: 0.6723, instance_loss: 0.0034, weighted_loss: 0.5051, 
batch 4499, loss: 1.9661, instance_loss: 0.0271, weighted_loss: 1.4814, 
batch 4999, loss: 2.6897, instance_loss: 0.5587, weighted_loss: 2.1569, 
batch 5499, loss: 0.7537, instance_loss: 0.0743, weighted_loss: 0.5839, 
batch 5999, loss: 1.2648, instance_loss: 0.0876, weighted_loss: 0.9705, 
batch 6499, loss: 0.3268, instance_loss: 0.0003, weighted_loss: 0.2452, 
Epoch 0 Summary: train_loss: 1.2140, train_clustering

In [3]:
#resnet +Clam
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_resnet",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/resnet_clam")



batch 499, loss: 2.3092, instance_loss: 0.6714, weighted_loss: 1.8998, 
batch 999, loss: 1.8042, instance_loss: 0.2362, weighted_loss: 1.4122, 
batch 1499, loss: 1.7083, instance_loss: 0.2915, weighted_loss: 1.3541, 
batch 1999, loss: 0.3403, instance_loss: 0.6389, weighted_loss: 0.4149, 
batch 2499, loss: 0.2482, instance_loss: 0.2826, weighted_loss: 0.2568, 
batch 2999, loss: 2.5312, instance_loss: 0.1011, weighted_loss: 1.9237, 
batch 3499, loss: 0.7858, instance_loss: 0.0579, weighted_loss: 0.6038, 
batch 3999, loss: 1.3367, instance_loss: 0.0219, weighted_loss: 1.0080, 
batch 4499, loss: 1.0077, instance_loss: 0.0119, weighted_loss: 0.7588, 
batch 4999, loss: 0.6614, instance_loss: 0.0121, weighted_loss: 0.4991, 
batch 5499, loss: 1.9250, instance_loss: 0.0294, weighted_loss: 1.4511, 
batch 5999, loss: 2.5681, instance_loss: 0.0288, weighted_loss: 1.9333, 
batch 6499, loss: 0.4340, instance_loss: 0.0399, weighted_loss: 0.3354, 
Epoch 0 Summary: train_loss: 1.2849, train_clusteri

In [4]:
#resnet +ClamSimple
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam, ClamSimple

df=pd.read_csv("F:/data/train_stratified.csv")

model=ClamSimple(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_resnet",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/resnet_clam_simple")



batch 499, loss: 0.6204, instance_loss: 0.0036, weighted_loss: 0.4662, 
batch 999, loss: 1.1094, instance_loss: 0.0258, weighted_loss: 0.8385, 
batch 1499, loss: 2.0785, instance_loss: 0.1820, weighted_loss: 1.6044, 
batch 1999, loss: 3.9448, instance_loss: 0.0154, weighted_loss: 2.9624, 
batch 2499, loss: 0.9333, instance_loss: 0.0129, weighted_loss: 0.7032, 
batch 2999, loss: 0.4714, instance_loss: 0.0037, weighted_loss: 0.3545, 
batch 3499, loss: 1.2211, instance_loss: 0.4860, weighted_loss: 1.0373, 
batch 3999, loss: 0.2751, instance_loss: 0.0099, weighted_loss: 0.2088, 
batch 4499, loss: 1.1410, instance_loss: 0.0528, weighted_loss: 0.8690, 
batch 4999, loss: 0.6694, instance_loss: 0.0135, weighted_loss: 0.5055, 
batch 5499, loss: 0.8929, instance_loss: 0.0591, weighted_loss: 0.6844, 
batch 5999, loss: 0.4881, instance_loss: 0.0003, weighted_loss: 0.3662, 
batch 6499, loss: 0.4126, instance_loss: 0.0105, weighted_loss: 0.3121, 
Epoch 0 Summary: train_loss: 1.2674, train_clusteri

In [5]:
#resnext +Clam
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam

df=pd.read_csv("F:/data/train_stratified.csv")

model=Clam(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_resnext",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/resnext_clam")



batch 499, loss: 0.8933, instance_loss: 0.4965, weighted_loss: 0.7941, 
batch 999, loss: 1.8035, instance_loss: 0.1439, weighted_loss: 1.3886, 
batch 1499, loss: 0.4329, instance_loss: 0.0632, weighted_loss: 0.3405, 
batch 1999, loss: 0.6457, instance_loss: 0.0442, weighted_loss: 0.4953, 
batch 2499, loss: 1.6222, instance_loss: 0.1230, weighted_loss: 1.2474, 
batch 2999, loss: 0.6144, instance_loss: 0.0153, weighted_loss: 0.4646, 
batch 3499, loss: 0.3766, instance_loss: 0.0075, weighted_loss: 0.2843, 
batch 3999, loss: 2.0523, instance_loss: 0.5587, weighted_loss: 1.6789, 
batch 4499, loss: 1.8695, instance_loss: 0.0134, weighted_loss: 1.4054, 
batch 4999, loss: 3.8495, instance_loss: 0.0209, weighted_loss: 2.8923, 
batch 5499, loss: 1.0813, instance_loss: 0.0018, weighted_loss: 0.8115, 
batch 5999, loss: 0.1948, instance_loss: 0.0085, weighted_loss: 0.1482, 
batch 6499, loss: 1.9097, instance_loss: 0.8302, weighted_loss: 1.6399, 
Epoch 0 Summary: train_loss: 1.1907, train_clusteri

In [6]:
#resnext +ClamSimple
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import Clam, ClamSimple

df=pd.read_csv("F:/data/train_stratified.csv")

model=ClamSimple(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_resnext",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/resnext_clam_simple")



batch 499, loss: 1.0918, instance_loss: 0.0052, weighted_loss: 0.8201, 
batch 999, loss: 1.3370, instance_loss: 0.0144, weighted_loss: 1.0064, 
batch 1499, loss: 1.6805, instance_loss: 0.2232, weighted_loss: 1.3162, 
batch 1999, loss: 1.6057, instance_loss: 0.0513, weighted_loss: 1.2171, 
batch 2499, loss: 0.4889, instance_loss: 0.0046, weighted_loss: 0.3678, 
batch 2999, loss: 0.3443, instance_loss: 0.0029, weighted_loss: 0.2589, 
batch 3499, loss: 1.5719, instance_loss: 0.0027, weighted_loss: 1.1796, 
batch 3999, loss: 0.5580, instance_loss: 0.0088, weighted_loss: 0.4207, 
batch 4499, loss: 1.4256, instance_loss: 0.0860, weighted_loss: 1.0907, 
batch 4999, loss: 0.9355, instance_loss: 0.0404, weighted_loss: 0.7117, 
batch 5499, loss: 1.8540, instance_loss: 0.0132, weighted_loss: 1.3938, 
batch 5999, loss: 0.6841, instance_loss: 0.0032, weighted_loss: 0.5139, 
batch 6499, loss: 0.2815, instance_loss: 0.0035, weighted_loss: 0.2120, 
Epoch 0 Summary: train_loss: 1.2896, train_clusteri

In [ ]:
#efficientNet +Clam +sigmoid
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import ClamSigmoid

df=pd.read_csv("F:/data/train_stratified.csv")

model=ClamSigmoid(
    feature_vector_length=1280,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_effnet",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/effnet_clam_sigmoid")

c:\Users\user\.julia\conda\3\lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(




batch 499, loss: 0.7109, instance_loss: 0.6099, weighted_loss: 0.6857, 
batch 999, loss: 1.3387, instance_loss: 0.6602, weighted_loss: 1.1691, 
batch 1499, loss: 1.5547, instance_loss: 0.4057, weighted_loss: 1.2675, 
batch 1999, loss: 0.7500, instance_loss: 0.5234, weighted_loss: 0.6933, 
batch 2499, loss: 1.0222, instance_loss: 0.1953, weighted_loss: 0.8155, 
batch 2999, loss: 1.7783, instance_loss: 0.3435, weighted_loss: 1.4196, 
batch 3499, loss: 1.5414, instance_loss: 0.0399, weighted_loss: 1.1660, 
batch 3999, loss: 0.5054, instance_loss: 0.0540, weighted_loss: 0.3925, 
batch 4499, loss: 0.9339, instance_loss: 0.2125, weighted_loss: 0.7536, 
batch 4999, loss: 1.1033, instance_loss: 0.6043, weighted_loss: 0.9786, 
batch 5499, loss: 0.6386, instance_loss: 0.0313, weighted_loss: 0.4867, 
batch 5999, loss: 1.1193, instance_loss: 0.0207, weighted_loss: 0.8447, 
batch 6499, loss: 2.2110, instance_loss: 0.0299, weighted_loss: 1.6657, 
Epoch 0 Summary: train_loss: 1.4623, train_clusteri

In [ ]:
#efficientNet +ClamSimple +sigmoid
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import ClamSimpleSigmoid

df=pd.read_csv("F:/data/train_stratified.csv")

model=ClamSimpleSigmoid(
    feature_vector_length=1280,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_effnet",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/effnet_clamsimple_sigmoid")

c:\Users\user\.julia\conda\3\lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(


batch 499, loss: 0.5859, instance_loss: 0.2144, weighted_loss: 0.4930, 
batch 999, loss: 1.7246, instance_loss: 0.2950, weighted_loss: 1.3672, 
batch 1499, loss: 1.9831, instance_loss: 0.4208, weighted_loss: 1.5925, 
batch 1999, loss: 1.2715, instance_loss: 0.1524, weighted_loss: 0.9917, 
batch 2499, loss: 1.4362, instance_loss: 0.0827, weighted_loss: 1.0978, 
batch 2999, loss: 1.6830, instance_loss: 0.0145, weighted_loss: 1.2659, 
batch 3499, loss: 0.4705, instance_loss: 0.0554, weighted_loss: 0.3667, 
batch 3999, loss: 0.4284, instance_loss: 0.0172, weighted_loss: 0.3256, 
batch 4499, loss: 1.7183, instance_loss: 0.1429, weighted_loss: 1.3244, 
batch 4999, loss: 2.1908, instance_loss: 0.0330, weighted_loss: 1.6514, 
batch 5499, loss: 8.8081, instance_loss: 0.0313, weighted_loss: 6.6139, 
batch 5999, loss: 0.4829, instance_loss: 0.0121, weighted_loss: 0.3652, 
batch 6499, loss: 0.3451, instance_loss: 0.0048, weighted_loss: 0.2601, 
Epoch 0 Summary: train_loss: 1.3150, train_clustering

In [3]:
#resNet +Clam +sigmoid
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import ClamSigmoid

df=pd.read_csv("F:/data/train_stratified.csv")

model=ClamSigmoid(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_resnet",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/resnet_clam_sigmoid")



batch 499, loss: 0.9060, instance_loss: 0.6541, weighted_loss: 0.8430, 
batch 999, loss: 0.5625, instance_loss: 0.6199, weighted_loss: 0.5768, 
batch 1499, loss: 1.1849, instance_loss: 0.5601, weighted_loss: 1.0287, 
batch 1999, loss: 1.3143, instance_loss: 0.5302, weighted_loss: 1.1183, 
batch 2499, loss: 0.3659, instance_loss: 0.5528, weighted_loss: 0.4126, 
batch 2999, loss: 2.1386, instance_loss: 0.5898, weighted_loss: 1.7514, 
batch 3499, loss: 1.3297, instance_loss: 0.3221, weighted_loss: 1.0778, 
batch 3999, loss: 1.2546, instance_loss: 0.3574, weighted_loss: 1.0303, 
batch 4499, loss: 1.3129, instance_loss: 0.1269, weighted_loss: 1.0164, 
batch 4999, loss: 1.8363, instance_loss: 0.3329, weighted_loss: 1.4604, 
batch 5499, loss: 1.3130, instance_loss: 0.0168, weighted_loss: 0.9890, 
batch 5999, loss: 1.5743, instance_loss: 0.0462, weighted_loss: 1.1923, 
batch 6499, loss: 1.4072, instance_loss: 0.0804, weighted_loss: 1.0755, 
Epoch 0 Summary: train_loss: 1.6853, train_clusteri

In [4]:
#resNet +Clamsimple +sigmoid
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import ClamSimpleSigmoid

df=pd.read_csv("F:/data/train_stratified.csv")

model=ClamSimpleSigmoid(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_resnet",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/resnet_clam_simple_sigmoid")

c:\Users\user\.julia\conda\3\lib\site-packages\torch\optim\lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(


batch 499, loss: 1.8519, instance_loss: 0.4554, weighted_loss: 1.5028, 
batch 999, loss: 1.4751, instance_loss: 0.3582, weighted_loss: 1.1958, 
batch 1499, loss: 0.4039, instance_loss: 0.0993, weighted_loss: 0.3278, 
batch 1999, loss: 1.9420, instance_loss: 0.3867, weighted_loss: 1.5532, 
batch 2499, loss: 2.1063, instance_loss: 0.5853, weighted_loss: 1.7261, 
batch 2999, loss: 1.1514, instance_loss: 0.0510, weighted_loss: 0.8763, 
batch 3499, loss: 0.2765, instance_loss: 0.0302, weighted_loss: 0.2149, 
batch 3999, loss: 0.3536, instance_loss: 0.0709, weighted_loss: 0.2829, 
batch 4499, loss: 1.0844, instance_loss: 0.0069, weighted_loss: 0.8150, 
batch 4999, loss: 0.7786, instance_loss: 0.0289, weighted_loss: 0.5912, 
batch 5499, loss: 0.2819, instance_loss: 0.0149, weighted_loss: 0.2151, 
batch 5999, loss: 0.7545, instance_loss: 0.1731, weighted_loss: 0.6092, 
batch 6499, loss: 1.9277, instance_loss: 0.5231, weighted_loss: 1.5766, 
Epoch 0 Summary: train_loss: 1.4634, train_clustering

In [5]:
#resnext +Clam +sigmoid
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import ClamSigmoid

df=pd.read_csv("F:/data/train_stratified.csv")

model=ClamSigmoid(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_resnext",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/resnext_clam_sigmoid")



batch 499, loss: 2.1190, instance_loss: 0.6362, weighted_loss: 1.7483, 
batch 999, loss: 1.7491, instance_loss: 0.5940, weighted_loss: 1.4604, 
batch 1499, loss: 1.3096, instance_loss: 0.3214, weighted_loss: 1.0625, 
batch 1999, loss: 0.3805, instance_loss: 0.2087, weighted_loss: 0.3376, 
batch 2499, loss: 3.1358, instance_loss: 0.3716, weighted_loss: 2.4447, 
batch 2999, loss: 3.3562, instance_loss: 0.1730, weighted_loss: 2.5604, 
batch 3499, loss: 0.3034, instance_loss: 0.1838, weighted_loss: 0.2735, 
batch 3999, loss: 0.0029, instance_loss: 0.0612, weighted_loss: 0.0175, 
batch 4499, loss: 1.6685, instance_loss: 0.0272, weighted_loss: 1.2581, 
batch 4999, loss: 1.2645, instance_loss: 0.0415, weighted_loss: 0.9587, 
batch 5499, loss: 3.7774, instance_loss: 0.0631, weighted_loss: 2.8489, 
batch 5999, loss: 1.5137, instance_loss: 0.0892, weighted_loss: 1.1576, 
batch 6499, loss: 1.2906, instance_loss: 0.0371, weighted_loss: 0.9773, 
Epoch 0 Summary: train_loss: 1.4410, train_clusteri

In [6]:
#resnext +Clam +sigmoid
import pandas as pd
from deep_learning.train.train import train
from deep_learning.models.attention_core.clam import ClamSimpleSigmoid

df=pd.read_csv("F:/data/train_stratified.csv")

model=ClamSimpleSigmoid(
    feature_vector_length=2048,
    dropout=0.1,
    k_sample=8,
    n_classes=6,
    subtyping=False
)



train(model=model,
      df=df,
      feature_path="F:/extracted_features_resnext",
      epochs=100,
      patience=6,
      min_delta=0.005,
      bag_weight=0.75,
      log_dir="F:/logs/resnext_clam_simple_sigmoid")



batch 499, loss: 1.6443, instance_loss: 0.6676, weighted_loss: 1.4001, 
batch 999, loss: 0.4669, instance_loss: 0.5745, weighted_loss: 0.4938, 
batch 1499, loss: 0.8090, instance_loss: 0.6551, weighted_loss: 0.7706, 
batch 1999, loss: 1.0848, instance_loss: 0.1779, weighted_loss: 0.8581, 
batch 2499, loss: 1.1033, instance_loss: 0.4806, weighted_loss: 0.9477, 
batch 2999, loss: 0.8568, instance_loss: 0.4752, weighted_loss: 0.7614, 
batch 3499, loss: 0.5151, instance_loss: 0.1792, weighted_loss: 0.4311, 
batch 3999, loss: 0.4349, instance_loss: 0.0879, weighted_loss: 0.3481, 
batch 4499, loss: 1.1581, instance_loss: 0.3812, weighted_loss: 0.9639, 
batch 4999, loss: 1.7563, instance_loss: 0.2377, weighted_loss: 1.3766, 
batch 5499, loss: 0.3293, instance_loss: 0.0198, weighted_loss: 0.2519, 
batch 5999, loss: 0.9832, instance_loss: 0.0208, weighted_loss: 0.7426, 
batch 6499, loss: 2.3556, instance_loss: 0.2738, weighted_loss: 1.8351, 
Epoch 0 Summary: train_loss: 1.3027, train_clusteri